## Function to Install and|OR load packages from CRAN
installNloadCRANpackages <- function(requiredPackages, lib) {
  for(p in requiredPackages) {
    if(p %in% rownames(installed.packages()) == FALSE) {
      cat("\nInstalling",p,"from CRAN in",lib,"...\n")
      .libPaths(lib)
      install.packages(p, repos = "https://cloud.r-project.org")
      suppressMessages(library(p, character.only = T))
    } else {
      cat("\nExcellent", p, "already installed. Loading", p, "...")
      suppressMessages(library(p, character.only = T))
    }}
  cat("\n\tDone setting up packages..\n\tWorking Directory is:",getwd())
}

## Function to Install and|OR load packages from BiocManager
installNloadBIOCpackages <- function(requiredPackages, lib) {
  for(p in requiredPackages) {
    if(p %in% rownames(installed.packages()) == FALSE) {
      cat("\nInstalling",p,"from BiocManager in",lib,"...\n")
      .libPaths(lib)
      BiocManager::install(p, dependencies = TRUE, verbose = TRUE)
      suppressMessages(library(p, character.only = T))
    } else {
      cat("\nExcellent", p, "already installed. Loading", p, "...")
      suppressMessages(library(p, character.only = T))
    }}
  cat("\n\tDone setting up packages..\n\tWorking Directory is:",getwd())
}

## Function to Install and|OR load packages from GitHub
installNloadGitHubpackages <- function(requiredPackages, lib) {
  for(p in requiredPackages) {
    pkg=str_split(p, "/")[[1]][2]
    if(pkg %in% rownames(installed.packages()) == FALSE) {
      cat("\nInstalling",pkg,"from GitHub:",p,"in",lib,"...\n")
      .libPaths(lib)
      devtools::install_github(p )
      suppressMessages(library(pkg, character.only = TRUE))
    } else {
      cat("\nExcellent", pkg, "already installed. Loading", pkg, "...")
      suppressMessages(library(pkg, character.only = TRUE))
    }}
  cat("\n\tDone setting up packages..\n\tWorking Directory is:",getwd())
}

#Function to read and filter fastp json reports based on taxRanks and Taxa
read_jsonFASTPReports <- function(jsonFilesdf,idColName) {
  #outputs=c()
  jsonQCList <- list()
  for(fileName in jsonFilesdf$QCjsonFilePath){
    output<-jsonFilesdf[match(fileName,jsonFilesdf$QCjsonFilePath),idColName]
    cat("Reading FASTP JSON from",output, "\n")
    # Initialize error flag
    error_occurred <- FALSE
    # Use tryCatch to handle errors
    tryCatch({
      #assign(output[1], rjson::fromJSON(file = fileName, flatten = TRUE))
      assign(output[1], jsonlite::fromJSON(txt = fileName, flatten = TRUE))
      qcList <- get(output)
      jsonQCList[[output]] <-qcList
    }, error = function(e) {
      cat("Error reading", output, ": ", e$message, "\n")
      error_occurred <- TRUE
    })
    # Skip to the next iteration if an error occurred
    if (error_occurred) {
      next
    }
  }
  return(jsonQCList)
}

#Function to extract summary statistics and generate means from a list generated by read_jsonQCReports() function above
read_summaryFASTPQCreports <- function(qcReportsList) {
  QCList <- list()
  listNames <- names(qcReportsList)
  for(fileName in listNames){
    output <- fileName
    cat("Extracting FASTP summary stats from",output, "\n")
      rawdata <- qcReportsList[[fileName]]$summary$before_filtering %>%
      as.data.frame() %>% rename_with( ~ paste0("raw.", .x)) %>% 
      mutate(sampleID = output) %>% select(sampleID, everything())
    trimmed <- qcReportsList[[fileName]]$summary$after_filtering %>% 
      as.data.frame() %>% rename_with( ~ paste0("trimmed.", .x))
    assign(output[1], bind_cols(rawdata,trimmed))
    QCdf <- get(output)
    QCList[[output]] <- QCdf }
  fastp_df <- QCList %>% bind_rows(.) %>% ungroup %>% 
    add_row(sampleID = 'MEANS', !!! colMeans(.[-1]))
  return(fastp_df)
}

#Function to read and filter fastp json reports based on taxRanks and Taxa
read_jsonHostile <- function(hostileQCjson) {
  jsonQCList <- list()
  for(fileName in hostileQCjson){
    # For each path and extract name
    output<-sub("\\.hostile\\.logs\\.json$", "", basename(fileName))
    cat("Reading HOSTILE JSON from",output, "\n")
    # Initialize error flag
    error_occurred <- FALSE
    # Use tryCatch to handle errors
    tryCatch({
      # Step 1: Read the entire content of the file
      file_content <- readLines(fileName, encoding = "UTF-8")
      # Step 2: Extract the JSON part using regular expressions 
      # Find the index of the first line (after one that starts with "[") and end line before the one that starts with "]"
      start_index <- grep("^\\[", file_content)[1] + 1
      end_index <- grep("^\\]", file_content)[1] - 1
      json_part <- file_content[start_index:end_index]
      # Step 3: Read the JSON part into R    
      assign(output[1], jsonlite::fromJSON(txt = json_part, flatten = TRUE))
      qcList <- get(output)
      jsonQCList[[output]] <-qcList
    }, error = function(e) {
      cat("Error reading", output, ": ", e$message, "\n")
      error_occurred <- TRUE
    })
    # Skip to the next iteration if an error occurred
    if (error_occurred) {
      next
    }
  }
  return(jsonQCList)
}

#Function to extract dataframe and merge a list generated by read_jsonHostile() function above
read_summaryHostileQCreports <- function(hostileReportsList) {
  QCList <- list()
  listNames <- names(hostileReportsList)
  for(fileName in listNames){
    output <- fileName
    cat("Extracting HOSTILE summary stats from",output, "\n")
    rawdata <- hostileReportsList[[fileName]]
    # Convert the list to a dataframe
    df <- as.data.frame(do.call(cbind, rawdata), stringsAsFactors = FALSE) %>%
      mutate(sampleID = output) %>% select(sampleID, everything())
    assign(output[1], df)
    QCdf <- get(output)
    QCList[[output]] <- QCdf }
  hostile_df <- QCList %>% bind_rows(.) %>% ungroup %>% mutate(across(where(is.list), as.character))
  return(hostile_df)
}

#Function to read and filter fastp json reports based on taxRanks and Taxa
read_jsonResfinder <- function(hostileQCjson) {
  jsonList <- list()
  for(fileName in hostileQCjson){
    # fileName="results_arg/resfinder/COVG156b.COVG156b.resfinder.json"
    # For each path and extract name
    output<-str_extract(fileName, "(?<=resfinder/)[^\\.]+")
    cat("Reading RESFINDER JSON from",output, "\n")
    # Initialize error flag
    error_occurred <- FALSE
    # Use tryCatch to handle errors
    tryCatch({
      assign(output[1], jsonlite::fromJSON(txt = fileName, flatten = TRUE))
      jList <- get(output)
      jsonList[[output]] <-jList
    }, error = function(e) {
      cat("Error reading", output, ": ", e$message, "\n")
      error_occurred <- TRUE
    })
    # Skip to the next iteration if an error occurred
    if (error_occurred) {
      next
    }
  }
  return(jsonList)
}

#Function to extract dataframe and merge a list generated by read_jsonResfinder() function above
filter_ResfinderReports <- function(resFinderReportsList) {
  
  # Function to standardize the length of lists
  standardize_length <- function(lst) {
    max_length <- max(sapply(lst, length))
    lapply(lst, function(x) {
      length(x) <- max_length
      return(x)  }) }
  
  # Function to convert a vector to a single string separated by a specified delimiter
  convert_to_string <- function(x, field, delimiter = ":") {
    if (is.vector(x[[field]]) || is.list(x[[field]])) {
      x[[field]] <- paste(x[[field]], collapse = delimiter)
    }
    return(x)
  }
  
  # Read ResFinder Reports; perform convert_to_string(); perform standardize_length()
  AMRList <- list()
  DrugsList <- list()
  listNames <- names(resFinderReportsList)
  for(fileName in listNames){
    # fileName="COVG158"
    output <- fileName
    cat("Extracting HOSTILE summary stats from",output, "\n")
    # Initialize error flag
    error_occurred <- FALSE
    # Use tryCatch to handle errors
    tryCatch({
      seq_regions_df <- lapply(resFinderReportsList[[fileName]]$seq_regions, function(region) {
        for (field in c("phenotypes","pmids")) {region <- convert_to_string(region, field)}
        return(region) }) %>% 
        lapply(., standardize_length) %>%
        bind_rows(., .id = "key") %>%
        mutate(sampleID = output) %>% select(sampleID, everything())
      phenotypes_df <- lapply(resFinderReportsList[[fileName]]$phenotypes, function(region) {
        for (field in c("amr_classes","seq_regions","seq_variations","ref_database")) {
          region <- convert_to_string(region, field, delimiter = ":") }
        return(region) }) %>% 
        lapply(., standardize_length) %>%
        bind_rows(., .id = "key") %>%
        mutate(sampleID = output) %>% select(sampleID, everything())
    }, error = function(e) {
      cat("Error reading", output, ": ", e$message, "\n")
      error_occurred <- TRUE
    })
    # Skip to the next iteration if an error occurred
    if (error_occurred) {
      next
    }
    AMRList[[output]] <- seq_regions_df 
    DrugsList[[output]] <- phenotypes_df}
  seqRegionsDF <- AMRList %>% bind_rows(.) %>% ungroup
  phenotypesDF <- DrugsList %>% bind_rows(.) %>% ungroup
  AMRDrugList <- list(seqRegionsDF = seqRegionsDF, phenotypesDF = phenotypesDF)
  return(AMRDrugList)
}

#Function to read and filter fastp json reports based on taxRanks and Taxa
read_resFinderFragGz <- function(resfinderfragReports) {
  outputList <- list()
  resFinderList <- list()
  for(file_path in resfinderfragReports){
    # file_path="results_arg/resfinder/COVG158/resfinder_kma/kma_trimethoprim.frag.gz"
    # file_path="results_arg/resfinder/COVG004/resfinder_kma/kma_misc.frag.gz"
    # Split the path by the directory separator
    path_parts <- strsplit(file_path, "/")[[1]]
    # Extract metadata from the file path
    drugClass <- sub("kma_", "", sub("\\.frag\\.gz", "", path_parts[length(path_parts)]))
    databaseID <- sub("_kma", "", path_parts[length(path_parts) - 1])
    sampleID <- path_parts[length(path_parts) - 2]
    output<-paste(sampleID,drugClass,sep = "_")
    
    cat("Reading", sampleID, databaseID, drugClass,"frag.gz file\n")
    # Initialize error flag
    error_occurred <- FALSE
    # Use tryCatch to handle errors
    tryCatch({
      # Read the gzipped file
      data <- read.csv(gzfile(file_path), sep = "\t" ,header = FALSE)
      # Add headers to the dataframe
      colnames(data) <- c("read", "mappedTemplates", "mappingScore", "startPosition", "endPosition", "templateID", "readID")
      # Add additional columns
      assign(output[1], mutate(data, sampleID = sampleID, databaseID = databaseID, drugClass = drugClass))
      AMRdf <- get(output)
    }, error = function(e) {
      cat("Error reading", sampleID, databaseID, drugClass,"frag.gz", ": ", e$message, "\n")
      error_occurred <- TRUE
    })
    # Skip to the next iteration if an error occurred
    if (error_occurred) {
      next
    }
    resFinderList[[output]] <- AMRdf
    AMRAbundance_df <- resFinderList %>% bind_rows(.) %>% ungroup %>% 
      select(sampleID, databaseID, drugClass, everything()) %>% distinct()
  }
  outputList[["AMRAbundance_df"]] <- AMRAbundance_df
  outputList[["resFinderList"]] <- resFinderList
  return(outputList)
}

# Function to merge rows
merge_rows <- function(df) {
  append_pipe <- function(x, readID) {
    if (length(x) == 1) {
      if (grepl("/1$", readID)) {
        return(paste0(x, "|"))
      } else {
        return(paste0("|", x))
      }
    } else {
      return(paste(x, collapse = "|"))
    }
  }
  
  df %>%
    summarise(
      sampleID = first(sampleID),
      databaseID = first(databaseID),
      drugClass = first(drugClass),
      amrClass = first(name),
      read = append_pipe(read, first(readID)),
      mappedTemplates = append_pipe(mappedTemplates, first(readID)),
      mappingScore = append_pipe(mappingScore, first(readID)),
      startPosition = append_pipe(startPosition, first(readID)),
      endPosition = append_pipe(endPosition, first(readID)),
      templateID = first(templateID),
      readID = if (n() == 2) {
        paste(unique(sub("/[12]$", "", readID)), collapse = "|") %>% paste0("/1|2")
      } else if (n() == 1) {
        paste0(sub("/[12]$", "", readID), "/1|2")
      } else {
        stop(paste("Error while reading", unique(sub("/[12]$", "", readID)), ": we found", n(), "number of readIds..."), call. = FALSE)
      }
    )
}

#Function to read and filter Kreports based on taxRanks and Taxa
filter_Reports <- function(reportFilesdf,filteredTaxRanks,filteredTaxa,tool="tool",
                           sampleID="name",ReportFilePath="ReportFilePath",nCores=1)
  {
  cat("\n\tProceeding with filtering taxonomic groups:", toString(filteredTaxa),"\n",
      "\tThe following ranks will be retained:", toString(filteredTaxRanks),"\n")
  # outputs=c()
  # kreportList <- list()
  
  # Rename columns for consistency
  names(reportFilesdf)[names(reportFilesdf) == tool] <- "tool"
  names(reportFilesdf)[names(reportFilesdf) == sampleID] <- "sampleID"
  names(reportFilesdf)[names(reportFilesdf) == ReportFilePath] <- "ReportFilePath"
  
  logFileName=paste("filterReports_",format(Sys.time(), "%Y%m%d_%H%M%S"),".log", sep="")
  writeLines(c(""),logFileName)
  
  cat("\t",length(reportFilesdf$sampleID),"Samples from",toString(unique(reportFilesdf$tool[])),
      "classification are now being analysed...\n")
  cat("\t",length(reportFilesdf$sampleID),"Samples from",toString(unique(reportFilesdf$tool[])),
      "classification are now being analysed...\n", file = logFileName, append = TRUE)
  
  # Start a cluster for parallel processing
  myCluster <- makeCluster(nCores, type = "FORK")
  registerDoParallel(myCluster)
  
  # Ensure the cluster is stopped even if an error occurs
  on.exit(stopCluster(myCluster))
  
  # Parallel processing of reports
  kreportList0 <- foreach(fileName = reportFilesdf$sampleID) %dopar% {
    tryCatch({
      sink(file = logFileName, append=TRUE)
      # fileName="COVG004"
      # kreportlist <- list()
      sampleFile <- reportFilesdf$ReportFilePath[match(fileName,reportFilesdf$sampleID)]
      toolUsed <- reportFilesdf$tool[match(fileName,reportFilesdf$sampleID)]
      output <- paste(fileName,toolUsed,sep = "-")
      cat(paste(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "Processing", output, "...\n"))
      
      # Read and filter the report
      df <- read_report2(sampleFile, collapse = TRUE,
                         keep_taxRanks = filteredTaxRanks,
                         min.depth = 0,
                         filter_taxon = filteredTaxa,
                         has_header = NULL,
                         add_taxRank_columns = TRUE)
      #kreportlist[[output]] <- df
      #outputs <- c(outputs, output)
      sink()
      setNames(list(df), output)
      # list(output = df)
      }, error = function(e) {
        sink()
        cat("Error processing", fileName, ":", e$message, "\n", file = logFileName, append = TRUE)
        NULL
      })
  }
  kreportList <- unlist(kreportList0, recursive = FALSE)
  return(kreportList)
}

# Function to read Kreports and filter target pathogens: Under active dev...
filterTargetInReports <- function(reportFilesdf,filteredTaxa,tool="tool",
                           sampleID="name",ReportFilePath="ReportFilePath",nCores=1) {
  cat("\n\tProceeding with filtering taxonomic groups:", toString(filteredTaxa),"\n",
      "\tThe following ranks will be retained: All Ranks in", toString(filteredTaxRanks),"\n")
  outputs=c()
  kreportList <- list()
  names(reportFilesdf)[names(reportFilesdf) == tool] <- "tool"
  names(reportFilesdf)[names(reportFilesdf) == sampleID] <- "sampleID"
  names(reportFilesdf)[names(reportFilesdf) == ReportFilePath] <- "ReportFilePath"
  logFileName=paste("filterReports_",format(Sys.time(), "%Y%m%d_%H%M%S"),".log", sep="")
  writeLines(c(""),logFileName)
  cat("\t",length(reportFilesdf$sampleID),"Samples from",toString(unique(reportFilesdf$tool[])),
      "classification are now being analysed...\n")
  cat("\t",length(reportFilesdf$sampleID),"Samples from",toString(unique(reportFilesdf$tool[])),
      "classification are now being analysed...\n", file = logFileName, append = TRUE)
  # registerDoFuture()
  # plan("future::multicore", workers=nCores)
  myCluster <- makeCluster(nCores, type = "FORK")
  # clusterExport(cl, c("reportFilesdf", "read_report2"))
  registerDoParallel(myCluster)
  # kreportList <- lapply(reportFilesdf$ReportFilePath, function(fileName) {
  kreportList0 <- foreach(fileName = reportFilesdf$sampleID) %dopar% {
    sink(file = logFileName, append=TRUE)
    # fileName="SPL0001"
    kreportlist <- list()
    sampleFile<-reportFilesdf$ReportFilePath[match(fileName,reportFilesdf$sampleID)]
    toolUsed<-reportFilesdf$tool[match(fileName,reportFilesdf$sampleID)]
    output=paste(fileName,toolUsed,sep = "-")
    cat(paste(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "Processing", output, "\b...\n"))
    # assign(output[1], read.csv(sampleFile, sep = "\t", header = F))
    assign(output[1], read_report2(sampleFile, collapse = FALSE,
                                   min.depth = 0,
                                   filter_taxon = filteredTaxa,
                                   has_header = NULL,
                                   add_taxRank_columns = TRUE))
    df <- get(output)
    kreportlist[[output]] <- df
    outputs <- c(outputs, output)
    sink()
    kreportlist
  }
  stopCluster(myCluster)
  kreportList <- unlist(kreportList0, recursive = FALSE)
  return(kreportList)
}

# Function to read and filter kreport reports: select root; unclassified; domain; phylum
# The output is used in the generation of summary statistics about the taxonomic coverage of the runs.
read_KReports <- function(kreportFilesdf,idColName) {
  #outputs=c()
  kreportsList <- list()
  for(fileName in kreportFilesdf$ReportFilePath){
    output<-kreportFilesdf[match(fileName,kreportFilesdf$ReportFilePath),idColName]
    cat("Reading",output, "\n")
    report <- read.csv(file = fileName, header = F, sep = "\t", quote = "", 
                       col.names = c("percentage","cladeReads","taxonReads","taxRank","taxID","name"))
    report$name <- gsub('+5"',"+5", report$name, fixed=TRUE)
    # gsub("'","", report$name, fixed=TRUE)
    # cat("Processing step0 \n")
    if (all(c("name","taxRank") %in% colnames(report)) && !"taxLineage" %in% colnames(report)) {
      ## Kraken report
      report$depth <- nchar(gsub("\\S.*","",report$name))/2
      if (!all(report$depth == floor(report$depth))) {
        warning("Depth doesn't work out!")
        return(NULL)
      }
      # cat("Processing step1 \n")
      report$name <- gsub("^ *","",report$name)
      report$name <- paste(tolower(report$taxRank),report$name,sep="_")
      rownames(report) <- NULL
      ## make taxLineage path
      report$taxLineage <- report$name
      n <- nrow(report)
      depths <- report$depth
      taxLineages <- report$name
      taxLineages_p <- as.list(seq_along(report$name))
      
      depth_row_tmp <- c(1:25)
      
      # cat("Processing step2 \n")
      for (current_row in seq(from=1, to=nrow(report))) {
        dcr <- depths[current_row]
        depth_row_tmp[dcr+1] <- current_row
        if (dcr >= 1) {
          prev_pos <- depth_row_tmp[[dcr]]
          taxLineages_p[[current_row]] <- c(taxLineages_p[[prev_pos]], current_row)
        }
      }
      report$taxLineage <- sapply(taxLineages_p, function(x) paste0(taxLineages[x], collapse="|"))
      report <- rename_with(report, ~ paste(output, .x, sep = "."), any_of(c("percentage","cladeReads","taxonReads")))
      filePathOUT <- paste("./plotdata/abundance/allDomains/samples/",shortDate,"_",output,"_allTaxaReadAbundance.csv", sep = "")
      cat("Writing dataframe of",output," kreport...\n")
      write.table(report, file = filePathOUT, row.names = FALSE, col.names= TRUE, sep = "\t", quote = FALSE)
    }
    assign(output[1], report)
    kList <- get(output)
    kreportsList[[output]] <- kList }
  # return(kreportsList)
  cat("Merging all extracted Kreports into one dataframe")
  reportColNames <- c("taxRank","taxID","name","depth","taxLineage")
  kreportDf <- reduce(kreportsList, full_join, by = reportColNames) %>% 
    mutate_if(is.numeric,coalesce,0) %>%
    select(name,taxID,taxRank,starts_with("SPL0"),depth,taxLineage)
  return(kreportDf)
}

# ARG Files
# Function to read ARG Files
readARGFiles <- function(argDataFilesList){
  #Read all ARG matched files
  outputs=c()
  outputList <- list()
  for(fileName in argDataFilesList){
    output<-gsub('\\..*','',basename(fileName))
    assign(output[1], read.csv(fileName, header = T, sep = "\t"))
    df <- get(output)
    outputList[[output]] <-df 
    outputs <- c(outputs, output)
  }
  return(outputList)
}

# Function to read ARG SAM file and filer based on MAPQ scores,
# read ARG Sequence Taxa Classification Kraken2 output file and merge both files
# Also generates krona input file and kreport input file
readARGSeqTaxFiles <- function(argSeqFiles, MAPQCutOff=100, argTaxFiles, nCores=1) {
  cat("\n\tProceeding with Reading, filtering and merging ARG Sequence and Taxonomy files",
      "\n\tARG alignment MAPQ cutoff has been set at:", toString(MAPQCutOff),"\n")
  logFileName=paste("readARGSeqTaxFiles_",format(Sys.time(), "%Y%m%d_%H%M%S"),".log", sep="")
  writeLines(paste(format(Sys.time(),"%Y-%m-%d %H:%M:%S"),"readARGSeqTaxFiles() function launched..."),logFileName)
  cat("\tProceeding with analysis of",length(argSeqFiles),"argSeqFiles from CARD-RGI mapping analysis and\n",
  "\t",length(argTaxFiles),"argTaxFiles from Kraken2 Taxonomic classification analysis of ARG Seqs...\n")
  cat("\t",length(argSeqFiles),"argSeqFiles from ARG mapping analysis with CARD-RGI are now being analysed...\n",
      "\t",length(argTaxFiles),"argTaxFiles from Kraken2 Taxonomic classification analysis of ARG Seqs...\n",
      file = logFileName, append = TRUE)
  #Read all ARG matched files
  # Initialize output dataframe
  outputdf <- data.frame() %>% tibble::as_tibble() %>% 
    add_column(sampleID = character(), mergedARGKraken2_file = character(), kraken2SOutput_file = character(), 
               kraken2Krona_file = character())
  
  # Start a cluster parallelization
  myCluster <- makeCluster(nCores, type = "FORK")
  registerDoParallel(myCluster)
  
  outputdf0 <- foreach(fileName = argSeqFiles, .combine = bind_rows) %dopar% {
    tryCatch({
      sink(file = logFileName, append=TRUE)
      # fileName = 'rgi/stats/COVG128_S10.seqs.temp.txt'
      output<-gsub('\\_.*','',basename(fileName))
      kraken2Output <- argTaxFiles[grep(output,argTaxFiles)]
      
      if (length(kraken2Output) == 1) {
        cat(paste(format(Sys.time(),"%Y-%m-%d %H:%M:%S"),"Reading data from",output,"\b: ARG SAM file",basename(fileName),
                  "\b; kraken2 output file",basename(kraken2Output),"\n"))
      } else if (length(kraken2Output) > 1) {
        cat(paste(format(Sys.time(),"%Y-%m-%d %H:%M:%S"),"Error: More than One kraken2 file matches",output,"sampleID\n"))
        return(NULL)
      } else {
        cat(paste(format(Sys.time(),"%Y-%m-%d %H:%M:%S"),"Error: No kraken2 file matches",output,"sampleID\n"))
        return(NULL)
      }
      
      # Reading ARG SAM file
      output0 <- data.table::fread(fileName, sep="\t", header=FALSE)
      filtered_data <- output0[!grepl("\\*", V3) & V5 > MAPQCutOff, ]
      filtered_data$V1 <- sub(" .*", "", filtered_data$V1)
      selected_columns <- filtered_data[, c("V1", "V2", "V3")]
      
      # Reading kraken2 output file
      output0 <- data.table::fread(kraken2Output, sep="\t", header=FALSE)
      
      # Merged ARG Seqs and Kraken2 report
      merged_data <- left_join(selected_columns, output0, by = c("V1" = "V2") ) %>% as.data.frame() %>%
        relocate(V1, .after = V1.y) %>% relocate(V2, .after = V3.x)
      merged_data_file = paste(getwd(),"/rgi/stats/",output,".ARG-Kraken2.merged.tsv", sep="")
      write.table(merged_data, file = merged_data_file, row.names = F, col.names = F, sep = "\t", quote = F)
      
      # Kraken2 Report
      kraken2Output0 <- merged_data %>% select(-c(V2,V3.x))
      kraken2Output0_file = paste(getwd(),"/rgi/stats/",output,".ARG-Kraken2.KSOutput.tsv", sep="")
      write.table(kraken2Output0, file = kraken2Output0_file, row.names = F, col.names = F, sep = "\t", quote = F)
      
      # Kraken2 Krona Input
      kraken2Krona <- merged_data %>% select(V1,V3.y)
      kraken2Krona_file = paste(getwd(),"/rgi/stats/",output,".ARG-Kraken2.krona.tsv", sep="")
      write.table(kraken2Krona, file = kraken2Krona_file, row.names = F, col.names = F, sep = "\t", quote = F)
      
      # Populate the output dataframe with Sample names and output paths
      outputdf <- tibble::tibble(sampleID = output, mergedARGKraken2_file = merged_data_file, 
                                 kraken2SOutput_file = kraken2Output0_file, kraken2Krona_file = kraken2Krona_file)
      sink()
      return(outputdf)
    }, error = function(e) {
      # Handle the error
      cat("An error occurred:", e$message, "\n")
    }, finally = {
      sink()
    })
  }
  
  stopCluster(myCluster)
  outputdf <- bind_rows(outputdf0)
  return(outputdf)
}

## Fuction to save a pheatmap
save_pheatmap_png <- function(x, filename, width=1200, height=1000, res = 150) {
  png(filename = paste(filename,".png",sep = ""), width = width, height = height, res = res, units = "in")
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}
save_pheatmap_pdf <- function(x, filename, width=1200, height=1000) {
  stopifnot(!missing(x))
  stopifnot(!missing(filename))
  cairo_pdf(file = paste(filename,".pdf",sep = ""), width = width, height = height, onefile = T)
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}

#' x      numeric vector for each slice
#' group  vector identifying the group for each slice
#' labels vector of labels for individual slices
#' col    colors for each group
#' radius radius for inner and outer pie (usually in [0,1]) 
#' 

donuts <- function(x, group = 1, labels = NA, col = NULL, radius = c(.7, 1)) {
  group <- rep_len(group, length(x))
  ug  <- unique(group)
  tbl <- table(group)[order(ug)]
  
  col <- if (is.null(col))
    seq_along(ug) else rep_len(col, length(ug))
  col.main <- Map(rep, col[seq_along(tbl)], tbl)
  col.sub  <- lapply(col.main, function(x) {
    al <- head(seq(0, 1, length.out = length(x) + 2L)[-1L], -1L)
    Vectorize(adjustcolor)(x, alpha.f = al)
  })
  
  plot.new()
  
  par(new = TRUE)
  pie(x, border = NA, radius = radius[2L],
      col = unlist(col.sub), labels = labels)
  
  par(new = TRUE)
  pie(x, border = NA, radius = radius[1L],
      col = unlist(col.main), labels = NA)
}
